image: Visual Studio 2019

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTDIR: C:\Qt\6.2\msvc2019_64
      COMPILER_NAME: msvc2019_64
      DATASLINGER_BOOST_PATH: C:\Libraries\boost_1_77_0

configuration:
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%QTDIR%\bin
  - call "%QTDIR%\bin\qtenv2.bat"
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - set make=nmake.exe

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%

  # Run qmake
  - qmake "CONFIG+=APPVEYOR" dataslinger.pro

# Build the project
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - '%make%'
  - ls -a
  - mkdir dataslinger_build
  - move %APPVEYOR_BUILD_FOLDER%\release\dataslinger.exe %APPVEYOR_BUILD_FOLDER%\dataslinger_build\dataslinger.exe
  - windeployqt %APPVEYOR_BUILD_FOLDER%\dataslinger_build
  - 7z a dataslinger_%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_BUILD_ID%_%COMPILER_NAME%_%CONFIGURATION%.zip "%APPVEYOR_BUILD_FOLDER%\dataslinger_build\*"

# Gather artifacts
artifacts:
  - path: dataslinger*.zip
    name: dataslinger
    type: File

# Deploy artifacts
deploy:
  provider: S3
  access_key_id: $(AWS_ACCESS_KEY_ID)
  secret_access_key: $(AWS_SECRET_ACCESS_KEY)
  bucket: $(AWS_S3_BUCKET_NAME)
  region: us-east-1
  unzip: false
  set_public: true
  folder: windows
  artifact: dataslinger
