environment:
  matrix:
    - QTDIR: C:\Qt\5.11.2\msvc2017_64
      COMPILER_NAME: msvc2017_64

configuration:
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat"
  - set make=nmake.exe

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%

  # Run qmake
  - qmake CONFIG+=%CONFIGURATION% dataslinger.pro

# Build the project
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - '%make%'
  - ls -a

# TODO
#  - move geometrize_installer.exe geometrize_installer_%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_BUILD_ID%_%COMPILER_NAME%_%CONFIGURATION%.exe

# Gather artifacts
artifacts:
  - path: '**\dataslinger*.exe'
    name: dataslinger
    type: File

# Deploy artifacts
deploy:
  provider: S3
  access_key_id: $(AWS_ACCESS_KEY_ID)
  secret_access_key: $(AWS_SECRET_ACCESS_KEY)
  bucket: $(AWS_S3_BUCKET_NAME)
  region: us-east-1
  unzip: false
  set_public: true
  folder: windows
  artifact: dataslinger