sudo: required
dist: trusty
language: cpp

# Setup build matrix
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libstdc++-7-dev
        - boost1.68
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  
  - os: linux
    addons:
      apt:
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - libstdc++-8-dev
        - boost1.68
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  # Set compilers
  - eval "${MATRIX_EVAL}"
  - echo $CC
  - echo $CXX
  
  # Get Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq --force-yes; fi

install:
  # Install Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt510base qt510svg qt510imageformats qt510tools; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt510/bin/qt510-env.sh; fi

script:
  # Build the application
  - qmake "CONFIG+=TRAVIS" dataslinger.pro
  - make CC=${CC} CXX=${CXX} LINK=${CXX}