sudo: required
dist: bionic
language: cpp

# Setup build matrix
matrix:
  include:  
  - os: linux
    addons:
      apt:
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - libstdc++-8-dev
        - boost1.68
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  # Set compilers
  - eval "${MATRIX_EVAL}"
  - echo $CC
  - echo $CXX
  
  # Get Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.6-bionic -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq --force-yes; fi

install:
  # Install Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgl1-mesa-dev qt512base qt512svg qt512imageformats qt512tools; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt512/bin/qt512-env.sh; fi

script:
  # Build the application
  - qmake "CONFIG+=TRAVIS" dataslinger.pro
  - make CC=${CC} CXX=${CXX} LINK=${CXX}
